services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "none"

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    environment:
      - DATABASE_URL=mssql+pyodbc://sa:gatineosFofineos@db:1433/eLibrosDB?driver=ODBC+Driver+17+for+SQL+Server

  db:
    mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: mssqlserver
    hostname: eLibrosDB
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "gatineosFofineos"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"


volumes:
   mssql-data: null
